Dealing with sealed type classes in Kotlin code
MercuryTechnologies/moat pull request #5
Opened 2021-04-08 22:40 UTC by chiroptical

When you have a sum-of-products type it isn't currently possible to build the right sealed type class.

```haskell
data Enum
  = A RecA
  | B RecB

data RecA =
  RecA
    { fieldA0 :: Int,
      fieldA1 :: Int
    }

data RecB =
  RecB
    { fieldB0 :: Int,
      fieldB1 :: Int
    }
```

If we want Parcelize/Serializable for each of these, we need to generate the following code

```kotlin
@Serializable(with = EnumSerializer::class)
sealed class Enum : Parcelable

@Parcelize
@Serializable
data class RecA(
    val fieldA0: Int,
    val fieldA1: Int,
) : Enum()

@Parcelize
@Serializable
data class RecB(
    val fieldB0: Int,
    val fieldB1: Int,
) : Enum()
```

Currently the AST can't generate the `RecA` code directly from the `Enum`. I am using `OtherInterface` to pass the name of the parent enum to the children. Ideally, we would generate the code directly but I don't have enough experience with this code to modify the AST yet.

TODO

- [ ] Get the parent enum printing correctly
- [ ] Add more golden tests to make sure we don't break other code

2021-04-09 15:02 UTC, chiroptical commented on src/Moat.hs
> +      LinkEnumInterface i -> i ++ "()"
I don't see why a `RawInterface String` would need to be a `ConE`. I want to be able to use the string directly. A `LinkEnumInterface` is useful when you need to create a `sealed class` that links to a parent enum.

2021-04-09 15:03 UTC, chiroptical commented on src/Moat.hs
> +      RawAnnotation s -> s
Similar logic as above. We need to do some funny stuff to get the Serializable annotation on a parent sealed class

2021-04-09 15:04 UTC, chiroptical commented on src/Moat/Class.hs
> -import qualified Data.List.NonEmpty as NE
Enabled -Wall. Just cleaning up.

2021-04-09 15:04 UTC, chiroptical commented on src/Moat/Types.hs
> +  | LinkEnumInterface String
TODO: Add comment here

2021-04-12 16:12 UTC, parsonsmatt requested changes
Great job on the tests!

The code and implementation looks fine, but we're moving away from type safety towards `String` mashing, which makes me uneasy. I'd prefer to see *more* structured datatypes, or at least `newtype Annotation = Annotation String`.

The implementation itself seems good, aside from that.

We should be keeping the .cabal file in the repo.

2021-04-12 16:12 UTC, parsonsmatt commented on src/Moat/Pretty/Kotlin.hs
> -        ++ prettyInterfaces ifaces
This seems to be the core change to the functionality in this PR.

Summarizing my understanding, we've somewhat simplified the representation: beforehand, we'd check to see if we had `cases = []`, and if so, make the sealed class, with: `annotations ++ "sealed class" ++ type header ++ interfaces`.

Now we omit that check and instead ask `allConcrete cases` (and `all pred [] == True`, so this hits), and then render `annotations ++ "sealed class " ++ header ++ interfaces`.

So we have a new `otherwise` case, which is selected whenever any `case` is not concrete. This does:

```
annotations ++ "enum class " ++ header ++ interfaces ++ render cases
```

This seems reasonable to me, though I don't know Kotlin.

2021-04-12 16:22 UTC, chiroptical commented on src/Moat.hs
> +      LinkEnumInterface i -> i ++ "()"
I was unfamiliar with this `lift` function. I will try to get the extra type safety using `Annotation` etc back in. I am very new to TH so I appreciate the input!

2021-04-12 16:24 UTC, parsonsmatt commented on src/Moat.hs
> +      LinkEnumInterface i -> i ++ "()"
No worries 😄 

There's a GHC extension to `DeriveLIft` that will be useful - probably need to attach it to all the relevant datatypes.

2021-04-12 19:57 UTC, chiroptical commented on .gitignore
> +moat.cabal
Fixed in 3da2c80

2021-04-12 20:48 UTC, chiroptical commented on src/Moat/Pretty/Kotlin.hs
> -        ++ prettyInterfaces ifaces
Exactly!

2021-04-12 20:49 UTC, chiroptical commented on src/Moat/Pretty/Kotlin.hs
> +        isConcrete (Concrete _ _) = True
Such a simple and elegant suggestion!

2021-04-12 21:06 UTC, chiroptical commented on src/Moat.hs
> +      LinkEnumInterface i -> i ++ "()"
Turns out this was already being used with the Swift codegen

2021-04-12 21:07 UTC, chiroptical commented on src/Moat/Types.hs
> +  | LinkEnumInterface String
Added in ac7e7c9

2021-04-12 21:08 UTC, chiroptical commented on src/Moat/Types.hs
> +      , newtypeAnnotations :: [String]
Now using `Interface`, `Protocol`, and `Annotation` directly in the AST. They are converted to `String` inside the Kotlin/Swift specific `pretty...` functions.

2021-04-12 21:09 UTC, chiroptical commented on src/Moat/Types.hs
> +      , enumAnnotations :: [String]
All set!

2021-04-12 23:14 UTC, parsonsmatt approved these changes
very nice!

2021-04-12 23:14 UTC, parsonsmatt commented on src/Moat.hs
> +    pure $ RecConE 'MoatEnum
this may be bike shedding but I think you can use a quasi quoter here - 

```suggestion
    [|MoatEnum
       { enumName = $(pure $ unqualName parentName)
        , enumTyvars = $(pure $ prettyTyvars tyVars)
        , -- eetc etc
        }
        |]
```

But, y'know, this *works* and it's fine :)

2021-04-12 23:14 UTC, parsonsmatt commented on src/Moat.hs
> +ifacesExp = fmap ListE <$> traverse Syntax.lift
i think we've got `instance (Lift a) => List [a] where lift = fmap ListE . traverse lift`, so I think this is merely `ifacesExp = lift`

2021-04-13 13:51 UTC, merged